name: ae353
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - scipy
  - sympy
  - matplotlib
  - notebook
  - ipywidgets
  - imageio
  - imageio-ffmpeg
  - pybullet
  - pip
  - git
  - playsound
  - imagemagick
  - pip:
    - git+https://github.com/meshcat-dev/meshcat-python.git

